### ISSUE TITLE
IO14: program hang on entry details screen

### ISSUE THREAD

**Issue by erathaowl** [strongbox-password-safe/Strongbox#385] opened 2020-07-29 19:46 UTC
After open an entry program hang on details screen: it's impossible to copy (or unmask) any field.
Also no modify or back buttons are present:

![image](https://user-images.githubusercontent.com/46474708/88845368-5494ad80-d1e4-11ea-8b40-aaf4467420bb.png)

Entry search, create a new group, moving entry and settings page are working.
Also ios auto-completion integration is working properly.
Otherwise create a new entry freeze the program with input in the first field:

![image](https://user-images.githubusercontent.com/46474708/88845634-ba813500-d1e4-11ea-901b-c429dc24966f.png)

Tests are done on iPhone XS Max with IOS 14 beta 3

**Comment by strongbox-mark** [comment] 2020-07-30 07:05
Thanks, this is a known issue at the moment with iOS14 beta 3. Hopefully Apple will fix in the next beta.

**Comment by erathaowl** [comment] 2020-07-31 08:08
Thank you for your reply, for completeness I point out that the program work without issues on iPadOS 14 beta 3

**Comment by shad0whawk** [comment] 2020-08-03 18:10
My app locks up as soon as I open the entry in portrait mode using a test device.  As someone else pointed out in another issue/thread, it seems to work fine if you place the app into landscape mode before opening the entry.  This could be a possible temporary solution for those that took the leap with their daily driver.

**Comment by strongbox-mark** [comment] 2020-08-03 19:34
OK, I believe I have a fix on the way... The issue is a very odd one, which I'm betting Apple will also fix in the next release, but there are still a few iOS 14 issues (less severe than this hang/crash). Early days...

**Comment by erathaowl** [comment] 2020-08-04 13:04
> it seems to work fine if you place the app into landscape mode before opening the entry.

Good workaround, thank you!

**Comment by shad0whawk** [comment] 2020-08-04 22:46
Still broken in iOS 14 Developer Beta 4

**Comment by danshan** [comment] 2020-08-05 01:22
> place the app into landscape mode

How can I place the app into landscape mode?

**Comment by danshan** [comment] 2020-08-05 01:23
> My app locks up as soon as I open the entry in portrait mode using a test device. As someone else pointed out in another issue/thread, it seems to work fine if you place the app into landscape mode before opening the entry. This could be a possible temporary solution for those that took the leap with their daily driver.

How can I place the app into landscape mode?

**Comment by shad0whawk** [comment] 2020-08-05 04:17
Disable Portrait Orientation Lock in control center, open the app, and physically turn your phone into landscape orientation so that long edge is horizontal to the ground. It works on both my 6S Plus 8, and 11 Max.

**Comment by coxde** [comment] 2020-08-05 04:50
Just for feedback: for me, after upgrading to iOS 14 beta 4, I can't open a database with yubikey (it keeps showing that it's being decrypted)!

**Comment by strongbox-mark** [comment] 2020-08-05 07:46
Thanks for the update. Probable fix in with Apple for review at the moment. ETA of about tomorrow morning.

**Comment by strongbox-mark** [comment] 2020-08-06 11:29
This should be fixed with 1.49.0 available now.

However please note there appears to be an issue with Nextcloud over WebDAV so don't upgrade just yet if you're using that.

**Closed by strongbox-mark** 2020-08-06 11:29 UTC

**Comment by erathaowl** [comment] 2020-08-06 12:27
> This should be fixed with 1.49.0 available now.
> 
> However please note there appears to be an issue with Nextcloud over WebDAV so don't upgrade just yet if you're using that.

Do you have submitted also update for strongbox pro?

**Comment by coxde** [comment] 2020-08-06 15:17
> This should be fixed with 1.49.0 available now.
> 
> However please note there appears to be an issue with Nextcloud over WebDAV so don't upgrade just yet if you're using that.

Thank you, but unfortunately Nextcloud over WebDAV does have problems. It says "Error reading database file:(com.MattRajca.DAVKit.error 404)"

**Comment by strongbox-mark** [comment] 2020-08-06 15:59
> > This should be fixed with 1.49.0 available now.
> > However please note there appears to be an issue with Nextcloud over WebDAV so don't upgrade just yet if you're using that.
> 
> Do you have submitted also update for strongbox pro?

Yes, update available for Family Sharing edition also... take note of the Nextcloud WebDAV warning before upgrading

**Comment by shad0whawk** [comment] 2020-08-06 19:07
Latest update works great on iOS 14 for my use case.  Will let you know if I stumble upon any other issues.

**Comment by erathaowl** [comment] 2020-08-07 14:23
> > > This should be fixed with 1.49.0 available now.
> > > However please note there appears to be an issue with Nextcloud over WebDAV so don't upgrade just yet if you're using that.
> > 
> > 
> > Do you have submitted also update for strongbox pro?
> 
> Yes, update available for Family Sharing edition also... take note of the Nextcloud WebDAV warning before upgrading

Thank you very much, work's great for me too
