### ISSUE TITLE
Sharing Credentials Subset (like KeepassXC) - KeeShare

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#288] opened 2020-02-27 11:49 UTC
Hi , 

Is something like that possible ?:
https://github.com/keepassxreboot/keepassxc/blob/develop/docs/QUICKSTART.md#user-content-using-sharing

Maybe also a suggestion for the OSX version

**Comment by mmcguill** [comment] 2020-02-27 19:17
I'm not sure this is something I want to add to Strongbox. KeePass is after all a personal password manager. Happy to keep this open for discussion.

**Comment by georgesnow** [comment] 2020-02-27 23:48
I have tended to shared database file. when I have logins etc that I need share. And since Strongbox as well as other macOS KeePass ports support dragging and dropping entries between different databases. I just keep a shared folder that I drag and drop into the shared database. 

The only place it doesn’t work for is iOS. I use my Mac daily, but the idea of copying entries or folder of entries between databases would be interesting for iOS. Just I can’t think of a good workflow for iOS.

**Comment by mmcguill** [comment] 2020-03-07 14:43
I'm fairly negative on this for iOS...

**Comment by strongbox-mark** [comment] 2021-02-22 18:21
Closing this a duplicate of #393

**Closed by strongbox-mark** 2021-02-22 18:21 UTC
Labels: Mac, enhancement

**Comment by artk47** [comment] 2021-11-01 18:17
I think "family" sharing falls down to personal password management tasks too. I believe it might be perspective direction for value-add features.

**Comment by chriswayg** [comment] 2022-08-21 09:47
KeeShare is an essential feature for us as well. We all transferred to KeePass from multiple years of 1Password usage, as finally the iOS and Android clients are on a similar level of quality and convenience, while 1Password is starting to abandon local vaults. The only feature we are missing is sharing a Group, a folder of credentials. 

_KeePassXC_'s  KeeShare does folder/group sharing and syncing about as well as 1Password, but it is limited to KeePassXC desktop clients. _KeePass2Android_ uses a similar, but different approach based on KeeAutoExec which  automatically opens a child database (using stored credentials) when opening the parent database.

I would prefer the KeeShare protocol, as it is already integrated into the most popular desktop cross platform application. 

I think this is certainly an **_essential feature_** for a "personal" password manager, as family sharing is very common and is also implemented well in Bitwarden, for example.
