### ISSUE TITLE
Feature request : Display icon for Passwort weakness

### ISSUE THREAD

**Issue by F3000** [strongbox-password-safe/Strongbox#279] opened 2020-02-18 22:32 UTC
An example zu can find in the attachment. Following colors exist : 

Red = weak
Orange =  not so weak
Yellow = medium
Light green = good 
Dark green = very good

You can also implement this into the the password generator 

![FA71AA82-310D-482B-A883-87115C1A4D2D](https://user-images.githubusercontent.com/8161283/74783502-2068a880-52a6-11ea-8032-849ef713299a.jpeg)

**Comment by mmcguill** [comment] 2020-02-22 16:09
Yes, it's a great idea but a duplicate of #19 I believe

**Closed by mmcguill** 2020-02-22 16:09 UTC

**Comment by F3000** [comment] 2020-02-23 11:11
Yes that’s right . It’s a duplicate
