### ISSUE TITLE
Long Delays on iOS 14.0.1

### ISSUE THREAD

**Issue by shad0whawk** [strongbox-password-safe/Strongbox#421] opened 2020-10-13 00:55 UTC
The Strongbox app on iOS 14.0.1. is very slow to respond when first opening as well as switching back to the app.  When I press the Strongbox icon, the application loading screen displays for roughly 4 - 7 seconds.  The same happens when I switch back to the application from another iOS application such as Safari.  It isn't always this slow but this happens quite often.  I never noticed this issue on iOS 13.  I've experienced this issue for some time now on iOS 14 and was hoping it would resolve itself as both iOS 14 and Strongbox mature, but that hasn't happened yet.  I'm trying to avoid uninstalling and reinstalling to see if it fixes the issue since that would require reconfiguring the app again.  

Any thoughts?  Has anyone else reported this behavior?

**Comment by strongbox-mark** [comment] 2020-10-13 10:50
I have noticed this myself, I thought it was just me using a dev version of the App, but it's definitely an iOS 14 issue. I will raise this with Apple and see what they say. In the meantime I'm hoping they fix in an upcoming release. 

Curious to hear if others are experiencing same. Let me know how re-install/restart goes.

**Comment by strongbox-mark** [comment] 2020-10-13 15:02
Would you guys mind sending me the debug info from your About screens... need to start collecting data. support@strongboxsafe.com will get me.

**Comment by dan-el** [comment] 2020-10-13 15:47
Hi Mark,

I also just sent in my debug info from my iPhone SE. I am NOT experiencing any delays. On neither of my 4 iOS/iPadOS devices.

They are all set up with the same settings which makes me think it might have something todo with a single setting or a combination of settings of Strongbox in combination with iOS/iPadOS 14.x

**Comment by strongbox-mark** [comment] 2020-10-13 18:45
Thanks @dan-el - Got it. I found the cause of the slow down and have a fix for it - Seems Apple have definitely been changing things under the hood.

**Comment by strongbox-mark** [comment] 2020-10-14 13:14
1.49.22 released now - you'll need to manually pull this update - Could you let me know if it fixed the issue for you @shad0whawk and @Slummi

**Comment by shad0whawk** [comment] 2020-10-14 19:48
I saw the update before I saw these comments. The last update appears to have fixed it. I’m not experiencing the delays anymore. I’ll let you know if I encounter them again over the next day or so. Nice job with the speedy fix!

**Comment by Slummi** [comment] 2020-10-15 09:10
I can‘t tell if 1.49.22 fixes the delays. I noticed the delays only one or two times directly after updating to iOS 14.0.

**Comment by strongbox-mark** [comment] 2020-10-15 09:47
Thanks @Slummi - Will keep open for a few days to monitor.

**Comment by shad0whawk** [comment] 2020-10-16 04:14
I can confirm that this latest build has definitely fixed my delay issues.

**Comment by strongbox-mark** [comment] 2020-10-16 08:34
Great to hear, thanks for the help, closing out...

**Closed by strongbox-mark** 2020-10-16 08:34 UTC
Labels: iOS
