### ISSUE TITLE
Mac: Autofill does not work for entries without username

### ISSUE THREAD

**Issue by janprzy** [strongbox-password-safe/Strongbox#516] opened 2021-05-01 08:50 UTC
Sometimes, I need to enter a password but not a username, e.g. to access my router's configuration website. In this case, my credentials from Strongbox are offered for autofill, but nothing happens when I click on them. I have to unlock the database, but the password is not filled in, so I have to resort to iCloud Keychain instead.

Edit: Forgot to mention that this is about the Mac version

**Comment by strongbox-mark** [comment] 2021-05-04 11:03
That sounds odd @janprzy - Will investigate. Do you know if this occurs on any other site or just this one?

**Comment by janprzy** [comment] 2021-05-04 11:08
Yes, it occurs on other sites as well. For example, Nextcloud sometimes requires me to enter my password, but not my username, to confirm some settings.
I will let you know if I find a website where this can be properly reproduces.

**Comment by strongbox-mark** [comment] 2021-05-04 16:27
I think I misunderstood. For these entries, you have also set a username, e.g. a username appears in the QuickType bar, or when you search you can see that there is a username. The username is not blank in your database. Right?

If so, I think this might just be down to a bad integration by the third party app/website (nextcloud or your router). In which case there isn't much that can be done from the Strongbox side.

**Comment by janprzy** [comment] 2021-05-04 17:10
Sorry, I phrased that poorly. My Nextcloud Account has a username that appears in the Autofill dropdown. However, in the case of my router, I do not need a username to log in and it is blank in the database.

**Comment by strongbox-mark** [comment] 2021-05-05 08:39
OK, makes some sense, and for your Router, if you were to add a dummy username, does that fix things?

**Comment by janprzy** [comment] 2021-05-05 08:45
Unfortunately not, it still doesn't work.

**Comment by strongbox-mark** [comment] 2021-05-05 08:47
Yeah, I think this is just going to be an issue with iOS AutoFill in general. Some webpages/apps do not integrate correctly or well with it. Your examples in particular. If other websites/apps are working then the issue is the third party website/app... There isn't anything Strongbox can do I'm afraid, you'd need to raise the issue with the third party.

**Comment by janprzy** [comment] 2021-05-05 08:51
I was hoping this was fixable, since iCloud Keychain works, but I guess I'll have to live with it for now. If I come across a public website with this issue, so you can test it yourself, I will let you know. Thanks anyways.

**Comment by strongbox-mark** [comment] 2021-05-05 09:53
Thanks @janprzy - Going to close this one out.

**Closed by strongbox-mark** 2021-05-05 09:53 UTC

**Comment by georgesnow** [comment] 2021-05-05 16:32
@janprzy do you use an ip in the url  foryour router? @strongbox-mark strongbox appears to use hostname match on url. Is there way to debug what’s getting passed to strongbox ?

so my router url is something like this:

http://1.1.1.1/login=?stuff/morestuff

I experience this issue I am wondering if it’s related the url matching

**Comment by janprzy** [comment] 2021-05-05 17:01
No, I use a hostname, but if I use the IP, it doesn't work either.
When I connect to my NAS using its IP, then log in with username+password, Strongbox works just fine, so I don't think this issue is about matching.
After all, in my case at least, Strongbox does find the correct entry, it just doesn't fill out the password field.

**Comment by janprzy** [comment] 2021-05-10 18:26
@strongbox-mark If you've got a Netflix Account, there is an instance that you might be able to test.

If you go to your account settings, then try to change e.g. age restrictions for a profile, it asks for the password, but not the username. Strongbox lets me select the correct entry, but the password is not filled out.

**Comment by strongbox-mark** [comment] 2021-05-17 10:36
Hi @janprzy - I see the issue on the Netflix site. I'm afraid this is an Apple/Third Party (Netflix) issue. Strongbox can only send back a username/password pair, it's up to Apple/Safari then to work with the website (Netflix) and it's structured HTML (form) to fill the password. In this case I'd say this is actually more of a Netflix issue but I can't be sure.
