### ISSUE TITLE
Strongbox cannot open PSAFE3 databases when the master password includes some non-ascii characters

### ISSUE THREAD

**Issue by csaona** [strongbox-password-safe/Strongbox#490] opened 2021-03-13 10:22 UTC
I had a PSAFE V3 database created with PasswordSafe (Android). The master password includes some non-ascii characters. I can open it with Password Gorilla in Ubuntu. However, when I try to open it with Strongbox I get an error saying that the password is incorrect.

The problem can be reproduced by creating an empty database in Password Gorilla in Ubuntu with the password ThisIsAI18NTestñçá and then trying to open it with Strongbox.

**Comment by strongbox-mark** [comment] 2021-03-13 11:38
We've had another person bring up this issue before on a support email, and the conclusion that we came to was that the issue was with the third party program. 

There are 2 things worth trying:

1) Create a database in the official Password Safe program on Windows with the same password. Can Strongbox then open it?
2) Do it the opposite way, can the official Password Safe program open a Strongbox created database with this password?

Are you in a position to try those experiments out?

**Comment by csaona** [comment] 2021-03-14 17:40
Hi

Unfortunately, I do not have access to a Windows computer. I've tried changing the input keyboard in the macbook in case it had something to do with the encoding, but nothing changed.

Is there a way to have Strongbox read the password from a file? Maybe using the command line? That way I could test with a file encoded with UTF8 and discard that is the issue.

**Comment by Ben-Voris** [comment] 2021-03-14 19:43
The [password safe project](https://www.pwsafe.org) produces a Linux client, which is what I use to update the safe I share with Strongbox.￼ Also, their MS-Windows client runs under Wine.￼

**Comment by csaona** [comment] 2021-03-15 17:00
You mean this one?: http://www.semanticgap.com/myps/

**Comment by Ben-Voris** [comment] 2021-03-15 17:39
https://github.com/pwsafe/pwsafe/releases/tag/1.12.0

**Comment by strongbox-mark** [comment] 2021-03-22 11:02
Hi @csaona - I've just taken a look at this. I used the official Password Safe program on Windows and Strongbox on Mac/iOS along with your suggested password above. It works fine both ways (created in Password Safe or Strongbox). 

This means there is an issue with the other apps you are using. They are not encoding these characters as UTF8 correctly (this is defined as the correct encoding in the Spec and Strongbox and Password Safe follow it). I'm afraid you'll need to chase up the authors of the alternative apps you are using and ask them to fix this issue. Unfortunately that might be a problem for them since they've probably got quite a few users using the problematic (wrong) encoding here.

On the Strongbox side, this is a definite wontfix or "not a bug". You can feel free to point those devs here or they can mail me and I can explain further, but it's just a simple incorrect choice of text encoding that's causing this.

**Closed by strongbox-mark** 2021-03-22 11:02 UTC
