### ISSUE TITLE
Hide on minimise (Mac)

### ISSUE THREAD

**Issue by SL93Code** [strongbox-password-safe/Strongbox#543] opened 2021-08-26 05:44 UTC
Since I installed the latest update Strongbox will stay in the dock on minimising, although it is setup to hide and only show in menu bar.

**Comment by strongbox-mark** [comment] 2021-08-31 12:15
Hi @SL93Code - This should be fixed in 1.15.21 available on the App Store now. Could you try it out?

**Comment by SL93Code** [comment] 2021-09-10 14:04
Works fine now. Is it possible to implement a function to minimize the app on copying any data?

**Comment by strongbox-mark** [comment] 2021-09-11 08:56
Thanks @SL93Code - Sure, could you just open a separate issue for that request?

**Comment by SL93Code** [comment] 2021-10-01 17:05
Issue seems to be back.

**Comment by SL93Code** [comment] 2021-10-01 17:10
It is gone if I disable and reactivate the feature in the settings.

**Comment by strongbox-mark** [comment] 2021-10-01 19:44
Hi @SL93Code - Could you be more specific, or please send a screen recording of the issue as I can't reproduce.

**Comment by SL93Code** [comment] 2021-10-05 05:19
I made screen record of the issue. Where can I send it to?

**Comment by strongbox-mark** [comment] 2021-10-05 07:07
Hi @SL93Code - Could you send to support@strongboxsafe.com? Thanks!

**Closed** 2021-12-01 14:33 UTC
