### ISSUE TITLE
Database modification are not updated on the application

### ISSUE THREAD

**Issue by pixel8383** [strongbox-password-safe/Strongbox#229] opened 2019-11-13 16:06 UTC
The workflow is: I have a database on Strongbox (let's call this db "A"). I edit a copy of this kdbx file on macOS (this way I will have a "B" version). The file is stored on nextcloud and it's accessible on iOS using the File app.
I don't have the "ability" to update the database "A" already existing on StrongBox but - moreover - if I delete it and try to open "B" from "Files" the result is that the database shown is still the "A".
I can't see the updated records even if Strongbox asked me to insert once again the master key when I tried to open the "B" file (since I deleted the "A" I don't have any db listed on the app).

[On the "Files" app, the file date is updated accordingly.]

Hint: to have it more clear, it would be useful to print on the db info the "last modified" date.

**Comment by mmcguill** [comment] 2019-11-14 10:32
Hi @pixel8383 - There’s definitely a issue or three with Nextcloud integration via iOS files. This is on Nextcloud.

I recommend you switch to using WebDAV for integration, it seems to work really well for people using Nextcloud.

**Comment by pixel8383** [comment] 2019-11-14 10:39
I will try to use the Nextcloud app instead of iOS Files app to open the database. What is weird is that the last modified date is being updated correctly on iOS Files, so you would not think of any bug. Thanks.

I have another question: when I open the version B of the database (in order to overwrite the A version already open in StrongBox), I cannot just import it. I have to delete the A database first OR I have to rename the B database while adding it. In any case I will have to type once again my master password. Is this wanted? Is there any way to "update" the database on StrongBox manually without the need to insert once again the master password?

**Comment by mmcguill** [comment] 2019-11-14 10:43
Using the Nextcloud app won’t work it’ll use the same method to link into Strongbox.

Why can’t you ‘just import it’ as you state above? 

Can you walk through the steps you are performing?

Again, highly recommend WebDAV

**Comment by pixel8383** [comment] 2019-11-14 10:46
Actually, I had to "bypass" the issue (iOS Files app) using the NextCloud app: this way the database was updated to version B. I clicked on my database, I asked for "Open with -> Strongbox" and in the end I added it with "Make a copy" (I don't like to link the device db).

**Comment by mmcguill** [comment] 2019-11-14 10:51
Make a Copy will make a one time local copy of the database (not linked or updated) in its current iOS Files state. 

If you need live/updated WebDAV is ideal.

**Comment by pixel8383** [comment] 2019-11-19 13:45
Thank you @mmcguill. Do you think it could be possible to have the "last modification" info inside the "Statistics" section? [KeePassXC displays this information there].

**Comment by mmcguill** [comment] 2019-11-21 10:32
I hope so, this is becoming a popular requested feature for people, the problem is managing it across so many storage providers, but hopefully I can do something with this as part of Offline/Merge work... Going to close this one off for now as I believe it is not a Strongbox issue.

**Closed by mmcguill** 2019-11-21 10:32 UTC
