### ISSUE TITLE
Mouse does not work in the Safari autofill popup

### ISSUE THREAD

**Issue by janprzy** [strongbox-password-safe/Strongbox#502] opened 2021-04-11 12:56 UTC
When using autofill in Safari, I sometimes have to select the login credentials from this popup window:

![Bildschirmfoto 2021-04-11 um 14 51 22](https://user-images.githubusercontent.com/41625296/114304802-74030a80-9ad5-11eb-93cb-11e6ec597e2a.png)

The window can be navigated with the keyboard, but the mouse is completely non-functional. Both clicking and scrolling do not work.

**Comment by strongbox-mark** [comment] 2021-04-12 09:58
Very strange, will investigate, thanks @janprzy

**Comment by strongbox-mark** [comment] 2021-04-16 14:43
Hi @janprzy  - Could you see if the latest MacOS version has helped this at all? version 1.15.9 on the App Store now.

**Comment by janprzy** [comment] 2021-04-16 18:18
Thanks for the quick update. So far, it seems to work. I will report back if it breaks again.

**Comment by janprzy** [comment] 2021-04-17 08:24
Bad news: I just used Strongbox to log in to my Synology's webinterface and the mouse did not work once again.

**Comment by strongbox-mark** [comment] 2021-04-17 11:30
OK, thanks @janprzy - I haven't been able to make the issue re-occur, it's only happened for me once unfortunately. 

One thing that might help, strangely, could you try to resize the dialog by grabbing the bottom right, lower corner of the window, see if you can do that. That seemed to have helped me, but I'm not sure if it's related.

I believe this may be an Apple issue/bug, but I'm not 100% sure.

**Comment by janprzy** [comment] 2021-04-18 08:13
I can not resize the dialog, both in situation where the mouse works and when it doesn't.

Something else I noticed: The issue only starts after Safari has been running for a while. It usually works right after launching Safari.

**Comment by strongbox-mark** [comment] 2021-04-19 11:23
Thanks for the extra detail @janprzy - Very odd indeed. Will continue investigating, as long as you can use the keyboard in this case this will take a lower priority.

**Comment by Doridian** [comment] 2021-11-10 15:55
I (think I) have this issue as well.
For me, this issue happens in the following condition (and ONLY in this condition):
- Strongox app becomes locked (due to sleep or user switch, etc)
- I try to auto-fill in Safari, it then uses my Apple Watch to unlock for that one credential
- The dialog is now "broken"

I can fix it by restarting Safari with the Strongbox app unlocked. Nothing else I tried fixes the dialog.

**Comment by strongbox-mark** [comment] 2021-11-10 16:37
Hi @Doridian - Could you verify you're running 1.16.3?

**Comment by Doridian** [comment] 2021-11-10 16:41
> Hi @Doridian - Could you verify you're running 1.16.3?

I was indeed on 1.16.2. Just updated (the App Store didn't prompt me, yet, so I manually went to the app page to update).
Will let you know if/when this re-occurs.

So far my quick tests have not shown the issues.

**Comment by strongbox-mark** [comment] 2021-11-10 16:45
Thanks @Doridian

**Comment by Doridian** [comment] 2021-11-11 00:09
@strongbox-mark Reproduction seems less reliable, but it just broke again for me.
Restarting Strongbox itself fixed it this time (which is good, restarting Safari is more difficult to re-open all my tabs)

**Comment by strongbox-mark** [comment] 2021-11-11 13:33
OK, thanks @Doridian - I have a few more things I'd like to try to fix this one. Expect those in the next release.

**Comment by strongbox-mark** [comment] 2021-11-15 20:42
Hi @Doridian & @janprzy - Could you upgrade to 1.16.4 to see if that fixes things here?

**Comment by Doridian** [comment] 2021-11-15 21:32
@strongbox-mark Still happening on 1.16.4. Can't find good repro steps, sadly, it just seems to happen at random.
This time it worked fine, even after unlocking and whatnot, but then randomly, without the DB re-locking, it stopped accepting mouse inputs.

**Comment by strongbox-mark** [comment] 2021-11-16 08:00
Thanks @Doridian - How often does it occur would you say, 50/50 or less? Is there any specific website it occurs on? 

Also, are you using QuickType (suggestions) or just regular select 'Strongbox...' to search for a credential?

**Comment by Doridian** [comment] 2021-11-16 08:05
@strongbox-mark
Once it started happening, it happens on all websites. I haven't found a pattern to see if any specific websites seem to trigger the problem.
I am not using QuickType, I always click the icon on a password field -> "Strongbox..."

**Comment by strongbox-mark** [comment] 2021-11-16 12:01
OK, thanks @Doridian - any extra info you come across appreciated

**Comment by strongbox-mark** [comment] 2021-11-16 12:09
@Doridian could you send your debug info to support@strongboxsafe.com ? You can find it under Strongbox > About Strongbox... menu item - Might be helpful

**Comment by Doridian** [comment] 2021-11-16 17:40
@strongbox-mark After some more playing around, it seems to break quite a bit when I plug my MacBook into my desk setup (1 screen over HDMI, 1 screen over Thunderbolt, 1 screen and a lot of USB peripherals through a Lenovo Thunderbolt dock)

**Comment by strongbox-mark** [comment] 2021-11-16 18:40
OK, thanks @Doridian - All this info is great

**Comment by Doridian** [comment] 2021-11-18 19:39
@strongbox-mark
It seems to me as if the USPS informed delivery login seems to be able to trigger this, somehow, as well.
Not sure if just coincidence or actual cause.
See: https://informeddelivery.usps.com/box/pages/intro/start.action ("Sign in" button)

**Comment by strongbox-mark** [comment] 2021-11-19 21:05
Thanks @Doridian - A quick test on this side seemed to work fine but we'll keep trying to reproduce the issue.

**Comment by Doridian** [comment] 2021-11-20 01:43
@strongbox-mark
Thanks so much :) If you want me to test a debug build, I can do that, or whatever might help.
But no worries, I got used to just using my keyboard to navigate the prompts.

**Comment by strongbox-mark** [comment] 2021-11-23 12:06
@Doridian Does a full reboot of your device help at all? 

Could you let me know the Safari version you're running?

Do you use the AutoFill "Wormhole"? If so, does disabling it help?

**Comment by Doridian** [comment] 2021-11-23 15:49
@strongbox-mark As mentioned previously.

Sometimes, restarting Strongbox helps. (Not often)
However, every time I try, restarting Safari helps (Cmd+Q and re-open it).
As restarting Safari is faster than rebooting my entire MacBook, I have not tried a full reboot, yet.
Given this information, do you think if I tried a full reboot it would give you more information?

As for the wormhole, yes, I am using it, otherwise I might wear out the button on my Apple Watch ;P
I disabled it for testing, to see if it helps or not.

**Comment by Doridian** [comment] 2021-11-23 16:40
Sadly, even with Wormhole disabled, it happened again. This time without any sleep in between.
Logged into USPS, fine. Logged into other websites, fine. Sleep, wake up, still works fine.
After a while, try USPS again, and now mouse input is broken.

**Comment by strongbox-mark** [comment] 2021-11-24 12:08
@Doridian could you send your debug info to support@strongboxsafe.com ? 

You can find it under Strongbox > About Strongbox > Copy Debug Info

**Comment by strongbox-mark** [comment] 2021-11-24 17:58
@Doridian - Believe I may have found the issue and it is related to Touch/Watch Unlock. If you use Manual Unlock instead of one of these convenience methods I believe this issue will not present itself. Have a fix in the works...

**Comment by Doridian** [comment] 2021-11-24 18:02
@strongbox-mark Sounds good. Also sent you the E-Mail you asked for.

**Comment by strongbox-mark** [comment] 2021-11-24 19:11
Thanks @Doridian - Yes, looks like some kind of combination of a change in Safari behaviour + some weirdness with requesting Touch/Watch ID in the way Strongbox has normally requested things...

**Comment by strongbox-mark** [comment] 2021-11-26 12:48
Hi @Doridian - We've just release 1.16.5, which I hope should fix this issue for you. Could you update on the App Store and let us know how it goes? You'll probably need to search for Strongbox and click in to it to see the Update button.

**Comment by Doridian** [comment] 2021-11-26 20:54
Updated first thing in the morning today. So far, it seems fixed. Used Watch unlock a couple times and it still accepts mouse input! :)

**Comment by strongbox-mark** [comment] 2021-11-27 10:18
That's awesome, fingers crossed. Let us know how it goes in a few days and we might be able to close this one out.

**Comment by Doridian** [comment] 2021-11-28 23:31
@strongbox-mark Sadly, it broke again :( It stayed working quite a bit longer than usual this time. Might be coincidence, though.

**Comment by strongbox-mark** [comment] 2021-11-29 09:52
Hi @Doridian - That's interesting. It's a tricky one to track down and I think we'll have to raise the issue with Apple. In the meantime we found another issue over the weekend and have a released a bug fix for it as 1.16.6. Would you be able to update and see how it goes? As usual, you'll probably need to search for Strongbox and click in to it to see the Update button.

**Comment by Doridian** [comment] 2021-12-02 06:15
@strongbox-mark Sorry for the late reply. Sadly, it did not improve the issue.
I also noticed sometimes after a sleep/wake cycle, the issue can fix itself somehow without a restart of either Safari or Strongbox.

**Comment by strongbox-mark** [comment] 2021-12-02 07:30
Thanks @Doridian - Just to confirm you were using 1.16.6. How often does this occur now?

**Comment by Doridian** [comment] 2021-12-02 15:49
@strongbox-mark It lasted around a day at first, then it lasted a couple hours (after it randomly fixed itself).
I don't tend to try and "fix' the problem myself as restarting my browser is more effort than just using my keyboard to navigate the dialogs.

**Comment by strongbox-mark** [comment] 2021-12-02 15:51
Thanks and 1.16.6?

**Comment by Doridian** [comment] 2021-12-02 15:52
@strongbox-mark Sorry, completely forgot. Yes. 1.16.6

**Comment by Kugelfang666** [comment] 2022-01-17 20:41
I‘m facing the same problem on both my and my wife’s MacBook running the lastest MacOS version. One more thing i notice: typically when this issue occurs stehe Strongbox autofill GUI is somewhat rendered at lower resolution than the rest of the screen.

**Comment by strongbox-mark** [comment] 2022-01-18 12:33
Hi @Kugelfang666 - would you be able to capture a (suitable redacted) screenshot of what you mean by lower resolution? 

Thanks!

**Comment by Kugelfang666** [comment] 2022-01-22 11:21
Hi.

I just encountered this problem today on www.prusa.com. I unlocked my DB via my Apple Watch on my Mac. You can see in the screen capture that I cannot operate the popup with my mouse but with the tabulator key on the keyboard and the enter key it works. When I select manual unlock, also that popup does only accept keyboard input.

https://user-images.githubusercontent.com/3289654/150636424-5fd30e8a-1bf5-4ec8-b828-d319cec3153c.mov

**Comment by Kugelfang666** [comment] 2022-01-22 11:23
I can temporarily fix this problem by fully terminating Safari (no more dot under the symbol in the dock) and starting it again. But it randomly reoccurs on both my and my wife's MacBook

**Comment by strongbox-mark** [comment] 2022-01-23 10:55
Thanks for the extra detail @Kugelfang666 - Any extra data points you can provide will be really helpful, especially as to when this occurs, if there's anything in particular in common when it happens.

**Comment by Kugelfang666** [comment] 2022-01-23 11:30
Will do so but to be honest at the moment this is all the insight I have. Underlining what the OP shared, this issues seems to happen after Safari was running for some time (days rather than hours). Is there any kind of log or so that I can generate and share with you next time I encounter this issue?

**Comment by strongbox-mark** [comment] 2022-01-24 08:40
It might be worth looking in the Console app when this happens to see if you can see anything odd under process (Safari) when this happens.

This might be one we need to send to Apple, I'm not sure it's a Strongbox issue unfortunately.

**Comment by Kugelfang666** [comment] 2022-01-29 15:00
the problem just reoccured and I did some check the console: it became flooded with:
![Bildschirmfoto 2022-01-29 um 16 00 00](https://user-images.githubusercontent.com/3289654/151665844-cd2def51-ae0f-4f7c-8bea-d9a8428f19e7.png)

**Comment by Kugelfang666** [comment] 2022-01-29 15:04
I can further confirm, completely terminating safari and restarting fixed the issue. Monitoring the console app, also the respective error message does not longer occur.

**Comment by strongbox-mark** [comment] 2022-01-30 10:27
Hi @Kugelfang666 - That's fantastic, thank you. I will report this to Apple, it doesn't seem like there's anything Strongbox can do here, but I might be wrong...

**Comment by strongbox-mark** [comment] 2022-01-31 19:25
@Kugelfang666 - 2 questions:

1. Does this seem to happen after your mac has gone to sleep/screen lock?
2. Are you using a second external monitor when this occurs?

**Comment by Kugelfang666** [comment] 2022-01-31 20:35
1. It happens randomly after the Mac was in operation for days, so for sure it was in sleep/screen locked multiple times, however this is not strictly reproducibly. Hence, not every time my Mac goes into sleep this happens
2. Both me and my wife are using our MacBooks 99% attached to an external thunderbolt screen. Hence, I cannot remember that it ever happened in any other use scenario

**Comment by georgesnow** [comment] 2022-10-14 17:11
Unfortunately, I still do experience this. I haven’t tried in a few weeks. But i changed workflow around the issue. I can try it again and if I can I will do screen capture

**Comment by Kugelfang666** [comment] 2022-10-14 17:49
H all, 

I can also confirm that this issues still is happening for me every now an then, full restart of Safari typically fixes it

**Comment by pictosun** [comment] 2022-12-21 17:02
Just started with Strongbox and the issue also comes up at my side. So - still an issue. Yes.

**Comment by janprzy** [comment] 2023-01-09 22:01
I can confirm this issue still exists, it just happened again.

**Comment by Kugelfang666** [comment] 2023-07-25 11:53
I haven’t encountered this for some time, would be ok to close from my end.

**Comment by strongbox-mark** [comment] 2023-07-25 14:33
I think we can close this one out too, please let me know if this is still occurring.

**Closed by strongbox-mark** 2023-07-25 14:33 UTC

**Comment by janprzy** [comment] 2023-07-25 21:13
Agreed, this can probably be closed for now. I haven't noticed the issue in a while.
