### ISSUE TITLE
App crashing on key loading/creating

### ISSUE THREAD

**Issue by azfar** [strongbox-password-safe/Strongbox#709] opened 2023-06-19 08:34 UTC
On Intel platform when I am importing RSA key or creating a new key (ED) from strongbox itself the app is crashing in both cases.

**Comment by strongbox-mark** [comment] 2023-06-19 09:52
Hi @azfar, yes, I saw your comment in #522 - Working towards a fix

**Comment by strongbox-mark** [comment] 2023-06-27 07:18
As mentioned in #522, the x86 crash issue should be fixed with 1.58.16 available on the App Store now. Could you test and let me know?

You might need to search for Strongbox on the App Store and click in, to see the "Update" button, it might not be an automatic update.

**Comment by strongbox-mark** [comment] 2023-12-08 07:14
This is looks quite stale and I believe the issue is fixed. Feel free to re-open if that's not the case.

**Closed by strongbox-mark** 2023-12-08 07:14 UTC
