### ISSUE TITLE
Issue with Favorites

### ISSUE THREAD

**Issue by JLWFuQrioea69ugsykvQcg** [strongbox-password-safe/Strongbox#733] opened 2023-10-29 20:52 UTC
Previously I think favorite entries were specified by including a tag labeled "FAVORITE". It looks like the behavior has changed in a recent build. Now when I add a tag labeled "FAVORITE" and save the entry, the tag disappears but the entry is not favorited. Existing entries with the "FAVORITE" tag are starred, but do not show the tag so I can't edit it directly. The bigger issue is when I favorite/unfavorite entries using a long press, the entries are saved to my Strongbox copy but revert after I open my database in Keepass and resave it. It seems that the change in Strongbox behavior is not compatible with how Keepass interprets the tags.

**Comment by strongbox-mark** [comment] 2023-10-30 12:56
Hi @JLWFuQrioea69ugsykvQcg - There appears to be two issues here:

1) Tag support for "Favorite" tag
2) The Favorite not syncing.

Issue 1 is by design and I don't foresee this changing without a very good reason. Could you tell why you would choose to manually edit the tag instead of using the quick convenient favourite/unfavourite buttons?

Issue 2 is more serious but I can't reproduce it at all. I'd need more detail. Are you definite your favourites are not being synced? Could you provide your debug info? Are you 100% sure the database has been synced (check the modified date)?

**Comment by JLWFuQrioea69ugsykvQcg** [comment] 2023-11-01 02:06
Thanks for the response.  

Item 1
I used the FAVORITE tag in Keepass to quickly access favorites prior to it being implemented in Strongbox. So manually editing the tag is habit. When I update the tag in Keepass, the modified time is altered. The same is not true using the long press favorite/unfavored option in Strongbox. This may cause issues syncing within Keepass between this another database. Is there a reason why the modified date is not updated when using this method to favorite the entry when it's still technically setting that tag to favorite or removing it?

Item 2
Here's what I was experiencing when I made the initial post and when I started my testing today. In Strongbox, if I set an entry as a favorite, using the menu and save the database, it will show up in  Keepass with the favorite tag. If I make changes to the database using Keepass, save it, open it in Strongbox, the entry no longer shows the favorite star, but I still see the favorite tag on the entry in Keepass. I performed some testing and in the beginning I was still experiencing this behavior. After multiple iterations of testing it seems to work as expected which is weird. I'll continue testing it to see if I can replicate the issue.

**Comment by strongbox-mark** [comment] 2023-11-01 10:08
OK, let's just focus on issue 1 then. That is definitely a bug if we're not setting the modified time and I can get that fixed in the next release.

**Comment by JLWFuQrioea69ugsykvQcg** [comment] 2023-11-01 23:13
Perfect! Hopefully that'll fix the other issue, which may be a result of my synchronization set up.

**Comment by strongbox-mark** [comment] 2023-11-02 06:53
Yes hope so... I've released an update (1.58.29) available on the App Store now, which I'm hoping will improve things for you, please let me know.

You might need to search on the App Store for Strongbox and click/tap into it to see the "Update" button, as it might not update automatically.

**Comment by JLWFuQrioea69ugsykvQcg** [comment] 2023-11-04 22:48
So far so good testing with the latest build. I'll close the ticket and open a new one if I run into any further issues.

**Closed** 2023-11-04 22:48 UTC
