### ISSUE TITLE
Strongbox doesn't get focus on Global Hot Key

### ISSUE THREAD

**Issue by daletman** [strongbox-password-safe/Strongbox#564] opened 2021-12-02 09:28 UTC
When I use the Global Hot Key (⌥⌘K), Strongbox does open, but the window is not focused so I can't interact with it until I click on it. Is this intended behavior?

**Comment by strongbox-mark** [comment] 2021-12-02 15:57
Sounds like a bug, we'll get it fixed for you in the next release.

**Comment by daletman** [comment] 2021-12-02 21:24
How to repoduce:
1. Open iTerm2
2. Enter a command which asks for password (for me it was ssh)
3. HotKey does not work

This could be a macOS Monterey thing, since Alfreds Global Hot Keys also reproducible stop working when the user is asked for password

**Comment by strongbox-mark** [comment] 2021-12-06 15:26
Hi @daletman 

Does this only happen when you are in the command line and a password is requested? I can't reproduce it in any other case.

**Comment by daletman** [comment] 2021-12-06 19:42
> Hi @daletman
> 
> Does this only happen when you are in the command line and a password is requested? I can't reproduce it in any other case.

Not to my knowledge.

**Comment by strongbox-mark** [comment] 2021-12-06 21:25
Sorry, could you clarify, have you seen this issue anywhere other than the stated command line requesting password situation?

**Comment by daletman** [comment] 2021-12-07 09:49
Yes, I've seen it in other places, but can't reproduce reliably.

**Comment by strongbox-mark** [comment] 2022-12-11 14:28
Hi @georgesnow @daletman - could you check if this is still an issue with 1.57.3?

**Comment by daletman** [comment] 2022-12-12 12:30
No, focus does work fine. But in general the search field doesn't get focus when opening Strongbox with the Shortcut. Is this a settings thing?

**Comment by strongbox-mark** [comment] 2022-12-12 13:50
OK, not sure if this is terminal related at all...

@daletman - could you check the Database > Start with Search menu item is checked?

**Comment by daletman** [comment] 2022-12-13 07:25
> OK, not sure if this is terminal related at all...
I'm pretty sure it was a general change (or Bug) in macOS Monterey that Hotkeys did not work when a Password field was focused. I had the same issue with my Global Hotkey for Alfred. I couldn't trigger it when any Password field was focused (or the Terminal prompt was asking for a password)

> @daletman - could you check the Database > Start with Search menu item is checked?
Ah yes, now it works, thanks you!

**Comment by strongbox-mark** [comment] 2022-12-13 08:20
Alright, I'll give @georgesnow a chance to comment but I think this is probably one to close soon.

**Comment by georgesnow** [comment] 2022-12-14 14:34
Hmm I did a quick test after doing the strongbox update. It doesn’t seem to work for me from iterm when there is password prompt within the terminal window.

however I tried 3 other apps with global hot keys same deal. The hot keys don’t work. This seems specific to terminals and password prompts. I will have to test it further to confirm.

**Comment by daletman** [comment] 2022-12-14 15:04
@georgesnow which macOS version are you using?

**Comment by strongbox-mark** [comment] 2022-12-27 14:13
I think I'm going to close this one out guys, seems like a weird OS level edge case.

**Closed by strongbox-mark** 2022-12-27 14:13 UTC

**Comment by djpowers** [comment] 2024-01-04 03:28
Chiming in late, but I just happened upon a similar issue recently where no apps (including Strongbox) would get focus when I tried to trigger their global hot keys while iTerm2 was the active application. I was seeing the same described behavior regardless of whether the terminal was displaying a password prompt.

For me, turning off "Secure Keyboard Entry" (under the iTerm2 menu item) fixed the problem. More info here: https://iterm2.com/documentation/2.1/documentation-menu-items.html
