### ISSUE TITLE
Latest Strongbox (1.50.9) crash at launch on iPhone 7 / iOS 14.2

### ISSUE THREAD

**Issue by eguaj** [strongbox-password-safe/Strongbox#436] opened 2020-12-09 19:39 UTC
Hi,

I just upgraded Strongbox to v1.50.9 and now I can't launch it : it crash whenever I open the app.

I tap the Strongbox app icon, the screen goes blue with the strongbox icon in white, then I immediatly return to the home screen.

- iPhone 7
- iOS 14.2

**Comment by tropi-github** [comment] 2020-12-09 19:55
I habe the Same problem.
iPhone 11
iOS 14.2

Herzliche Grüße

Thomas Antropius

Achte auf Sicherheit im Netz
Volks✔erschlüsselung®
Offene Initiative für Ende-zu-Ende-Sicherheit
https://www.volksverschluesselung.de/

**Comment by eguaj** [comment] 2020-12-09 20:00
If it helps, here are the 3 last messages as seen in Console.app:
```
---
erreur	20:56:14.572164+0100	Strongbox	Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x283fcbc00 UIStackView:0x104735cc0.centerX == UIView:0x10501ac10.centerX   (active)>",
    "<NSLayoutConstraint:0x283fcbca0 H:|-(>=20)-[UIStackView:0x104735cc0](LTR)   (active, names: '|':UIView:0x10501ac10 )>",
    "<NSLayoutConstraint:0x283fcbcf0 UIStackView:0x104735cc0.right >= UIView:0x10501ac10.right + 20   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283fcbcf0 UIStackView:0x104735cc0.right >= UIView:0x10501ac10.right + 20   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
---
par défaut	20:56:14.572339+0100	Strongbox	REFRESH: Refreshing entire table...
---
par défaut	20:50:40.739757+0100	Strongbox	*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[_NSPlaceholderData initWithContentsOfFile:options:maxLength:error:]: nil file argument'
*** First throw call stack:
(0x182d459d4 0x1966f6b54 0x183ee21e4 0x183f15f20 0x100bf75a4 0x100bf7448 0x100d3baa4 0x100cbf054 0x18297d298 0x18297e280 0x182923048 0x18292ff3c 0x182930704 0x1c93e2568 0x1c93e5874)
```

**Comment by strongbox-mark** [comment] 2020-12-09 20:03
Thank you for the reports and especially the console log. Aware of the issue and investigating the cause. Apologies for the inconvenience.

**Comment by strongbox-mark** [comment] 2020-12-09 21:27
Just an update. The issue has been found, it doesn't appear in development builds which is why it slipped through both testing and App Store review. It was due to some technical debt cleanup which in which I was a little over eager in cleaning up some files.

A fix is on the way but it could take Apple about 24 hours to review and release... If you can help it at all, please don't update.

**Comment by strongbox-mark** [comment] 2020-12-10 00:01
A fix is now available as 1.50.10 on the App Store. Please install, it should fix all issues.

**Comment by shad0whawk** [comment] 2020-12-10 00:29
Just updated to 1.50.10 and it still crashes.

**Comment by shad0whawk** [comment] 2020-12-10 00:30
FWIW I reverted to 1.50.8 while waiting for the update fix so that was my update path to 1.50.10. However it’s not working for me.

**Comment by shad0whawk** [comment] 2020-12-10 00:35
Ok weird. Updated the app because it showed 1.50.10 and then it crashed upon opening. Checked App Store again to verify build number. Went back to Strongbox and it crashed again. Sent in this report. Went back to App Store and it shows s up again as an update with same build number. Updated again and now it opens. Long story short—it works now. Maybe the App Store was still pulling in the previous build.

**Comment by eguaj** [comment] 2020-12-10 07:23
I confirm that v1.15.10 corrects this problem for me.

Thank you Mark for your reactivity!

**Comment by Slummi** [comment] 2020-12-10 08:21
Unfortunately I can't confirm that 1.15.10 fixes this issue.
I waited with the update to 1.15.9 due to the bug report. After shad0whawk and eguaj have confirmed that 1.15.10 works, I've just updated to that version and Stronbox crashes immediately when opening it. :(

**Comment by Slummi** [comment] 2020-12-10 08:27
OK, very wired. Same behavior as shad0whawk has described. After updating to 1.15.10 the app crashes. I checked again the App Store and got the update to 1.15.10 again. After the second update it's working now and I got a crash report after the first start of the app.

**Comment by Slummi** [comment] 2020-12-10 08:33
For the sake of completeness:
I just did the update on another device (iPhone 7) and it worked there the first time. The App Store doesn't offer me the update there a second time. Strange...

**Comment by strongbox-mark** [comment] 2020-12-10 09:34
Thanks @shad0whawk @Slummi - Can't explain the App Store second time download thing but I'm fairly sure 1.50.10 is ok... Cheers for your help everyone.

**Comment by tropi-github** [comment] 2020-12-10 09:47
Hi together,

the version 1.50.10 is working.
Trank you for fast fixing.

Herzliche Grüße

Thomas Antropius

#DenkeSelbst
Achte auf Sicherheit im Netz
Volks✔erschlüsselung®
Offene Initiative für Ende-zu-Ende-Sicherheit
https://www.volksverschluesselung.de/

**Comment by strongbox-mark** [comment] 2020-12-10 12:33
That's great, cheers. Closing out...

**Closed by strongbox-mark** 2020-12-10 12:33 UTC

**Comment by sindastra** [comment] 2021-06-22 08:03
> A fix is on the way but it could take Apple about 24 hours to review and release

I wonder what kind of "review" Apple did the first time, to not have caught such a startup crash... :D

On another note for the next time: Doesn't Apple provide an option to skip review or speed it up, for emergency updates? I thought I heard of something like that in the past.
