### ISSUE TITLE
iOS App Unable to Create New .kdbx Database when navigating SharePoint folders in UI

### ISSUE THREAD

**Issue by rafioso24** [strongbox-password-safe/Strongbox#394] opened 2020-08-19 18:00 UTC
I am trying create a new keepass database from the Strongbox iOS app in a shared web location.
I am using Sharepoint as the destination repository and connecting to it over WebDAV.

If I type in the full web address of the Sharepoint folder, and then click 'create database' the database is successfully created.
Full web address: _https://mysharepointsite.com/Shared%20Documents/Forms/_

**But if I type in the root web address, and then navigate to the destination subfolder (_Shared%20Documents/Forms_) using the Strongbox UI, There is an error creating the database (409 error in attached screenshot).**
Root web address: _https://mysharepointsite.com/_

![Error Creating Database](https://user-images.githubusercontent.com/5367007/90671334-2a01a780-e21a-11ea-8440-62be5c934eb5.jpg)
ngbox/issues

**Comment by strongbox-mark** [comment] 2020-08-20 18:44
Thanks for the report. Super strange. The WebDAV error codes are standard HTTP error codes and 409 is "Conflict"

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

There's no way this is due to using the same filename/database name and trying to create it twice, is there?

**Comment by rafioso24** [comment] 2020-08-24 15:41
I went in and created a totally unique database name, and ran into the same issue.
Also, I am using SharePoint 2013.

**Comment by strongbox-mark** [comment] 2020-08-24 15:44
Wow, ok, do you by any chance have access to the server logs? Anything interesting in there?

**Comment by rafwork1** [comment] 2020-08-28 20:46
Hey mark. I am switching over to this account. I am working on getting you those logs. In the meantime, I found this blog which may relate to what is going on.

https://stackoverflow.com/questions/6785036/reasons-for-a-409-conflict-http-error-when-uploading-a-file-to-sharepoint-using#:~:text=30-,Reasons%20for%20a%20409%2FConflict%20HTTP%20error%20when%20uploading,file%20to%20sharepoint%20using%20a%20.&text=I've%20googled%2C%20and%20it,path%20without%20a%20file%20name

I wonder if strongbox is not appending the proper filename at the end of the URL when I navigate through the sharepoint subfoldres.

**Comment by strongbox-mark** [comment] 2020-08-30 09:10
Thanks @rafwork1 - Hard to say what's happening here. Is there anyway for me to reproduce this on my side, or have test access to a similar server? Feel free to email support@strongboxsafe.com if you would prefer to follow up privately

**Comment by rafwork1** [comment] 2020-09-04 13:23
Sharepoint is throwing this exception : 
**System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)**

In order to reproduce this error, you would need a SharePoint 2013 server.
I know that you can create a SharePoint 2013 server to test with on Microsoft Azure. There is some cost associated with it, but Azure gives a free trial to first-time subscribers. Here is a video of someone setting up a SharePoint 2013 Server in Azure in ~1hour.
https://www.youtube.com/watch?v=MM0nmzT-QOU

**Comment by strongbox-mark** [comment] 2020-09-05 15:53
Thanks @rafwork1 - I hope to look into this shortly...

**Comment by strongbox-mark** [comment] 2020-09-09 16:19
This should be fixed in 1.49.9 @rafwork1 - Could you verify and close? 

You may need to search the App Store to get the updated version 1.49.9 - the update isn't released automatically to everyone.

**Comment by rafwork1** [comment] 2020-09-09 21:43
@strongbox-mark Yes, that fixed it. Thank you so much for your speedy reply and resolution!

**Comment by strongbox-mark** [comment] 2020-09-10 10:49
No worries! Glad it's working now.

**Closed by strongbox-mark** 2020-09-10 10:49 UTC
