### ISSUE TITLE
Sync reports reports an entry will be added but entry already exists.

### ISSUE THREAD

**Issue by Ben-Voris** [strongbox-password-safe/Strongbox#499] opened 2021-04-01 03:50 UTC
I edited an entry in my Password safe db to change my Source Forge password. The merge conflict report shows that an old entry will be added. 

![image](https://user-images.githubusercontent.com/31499002/113240855-c2f5a800-926a-11eb-957c-1a2bc94e22a2.png)

This shows the view from another system. 

![image](https://user-images.githubusercontent.com/31499002/113241265-942c0180-926b-11eb-9286-94d440b7feb3.jpeg)

This entry was involved in https://github.com/strongbox-password-safe/Strongbox/issues/463

Strongbox 1.52.10 Debug Information at 2021-03-31 22:01:24.874
--------------------
App Version: com.markmcguill.strongbox [1.52.10 (3045)@9e627fc]
--------------------
Device
--------------------
Model: iPad
CPU: arm64 v8
System Name: iOS
System Version: 14.4.2
--------------------
Preferences
--------------------
isHavePromptedAboutFreeTrial: 1
INNextHearbeatDate: 561444546.848978
migratedToNewPasswordGenerator: 1
WebKitOfflineWebApplicationCacheEnabled: 1
AppleKeyboardsExpanded: 1
isPro: 1
migratedLocalDatabasesToNewSystem: 1
numberOfEntitlementCheckFails: 0
passwordGenerationConfig: {length = 668, bytes = 0x62706c69 73743030 d4010203 04050607 ... 00000000 00000200 }
hasDoneProFamilyCheck: 1
showDatabasesSeparator: 1
AKLastIDMSEnvironment: 0
showPasswordByDefaultOnEditScreen: 1
com.apple.content-rating.MovieRating: 1000
migratedToNewQuickLaunchSystem: 1
promptedForCopyPasswordGesture: 1
DidMigrateToAppGroups: 1
WebKitShrinksStandaloneImagesToFit: 1
ApplePasscodeKeyboards: (
    "en_US@hw=US;sw=QWERTY"
)
AppleICUForce24HourTime: 1
com.apple.content-rating.ExplicitMusicPodcastsAllowed: 1
databaseCellTopSubtitle: 1
com.apple.content-rating.AppRating: 1000
collapsedSections: (
    0,
    0,
    0,
    0,
    0,
    0
)
applicationIdentifierPrefix: 4326J8XDF2
PKKeychainVersionKey: 4
AppleLanguages: (
    "en-US"
)
lastEntitlementCheckAttempt: 2021-03-31 19:17:42 +0000
AppleLocale: en_US
hasShownAutoFillLaunchWelcome: 1
DidCleanUpOldOfflineCacheFiles: 1
AppleKeyboards: (
    "en_US@hw=US;sw=QWERTY"
)
haveAttemptedMigrationToFullFileProtection: 1
autoFillQuickLaunchUuid: B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF
INNextFreshmintRefreshDateKey: 561862892.637621
com.apple.content-rating.ExplicitBooksAllowed: 1
useQuickLaunchAsRootView: 0
com.apple.content-rating.TVShowRating: 1000
showDatabaseStatusIcon: 1
showDatabaseIcon: 1
autoLockTimeSeconds: 600
hideTotp: 0
AKDeviceUnlockState: 1
migratedQuickLaunchToAutoFill: 1
iCloudWasOn: 1
safesMigratedToNewSystem: 1
endFreeTrialDate: 2017-09-26 03:39:44 +0000
fullFileProtection: 1
NSLanguages: (
    "en-US",
    en
)
safesList: {length = 7060, bytes = 0x62706c69 73743030 d4000100 02000300 ... 00000000 00001892 }
MSVLoggingMasterSwitchEnabledKey: 0
kMigratedYubiKeyEmergencyWorkaroundsToVirtualKeys: 1
AKLastEmailListRequestDateKey: 2018-09-27 05:10:46 +0000
NSPersonNameDefaultShortNameFormat: 1
AKLastCheckInAttemptDate: 2018-10-20 07:56:00 +0000
quickLaunchUuid: B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF
migratedOfflineDetectedBehaviour: 1
neverShowForMacAppMessage: 1
migratedDatabasesToNewStore: 1
tryDownloadFavIconForNewRecord: 1
NSInterfaceStyle: macintosh
AppleTemperatureUnit: Fahrenheit
hasMigratedDatabaseSubtitlesAug2020: 1
autoFillDidChangeDatabases: 0
safes: (
        {
        fileIdentifier = 0BwcD0j0uWrgDeW1LV3VKTmNTOVk;
        fileName = "BenPasswords.psafe3";
        isEnrolledForTouchId = 1;
        isTouchIdEnabled = 1;
        nickName = Ben;
        offlineCacheAvailable = 1;
        offlineCacheEnabled = 1;
        offlineCacheFileIdentifier = "A1605AEE-2911-47B7-90EC-3207A7AA6617";
        storageProvider = 0;
    },
        {
        fileIdentifier = 0BwcD0j0uWrgDeW1LV3VKTmNTOVk;
        fileName = "LesliePasswords.psafe3";
        isEnrolledForTouchId = 1;
        isTouchIdEnabled = 1;
        nickName = Leslie;
        offlineCacheAvailable = 1;
        offlineCacheEnabled = 1;
        offlineCacheFileIdentifier = "4CA644FA-2BD3-42D2-9444-F27EA6B4373B";
        storageProvider = 0;
    },
        {
        fileIdentifier = "2017 01 31 HP password-strongbox.dat";
        fileName = "2017 01 31 HP password-strongbox.dat";
        isEnrolledForTouchId = 1;
        isTouchIdEnabled = 1;
        nickName = "2017 01 31 HP password";
        offlineCacheAvailable = 0;
        offlineCacheEnabled = 0;
        offlineCacheFileIdentifier = "";
        storageProvider = 2;
    }
)
databaseCellSubtitle2: 3
launchCount: 361
easyReadFontForAll: 1
iCloudOn: 1
KeychainAccessibilityMigration: 1
copyPasswordOnLongPress: 1
AddingEmojiKeybordHandled: 1
PKUserHasDisabledPeerPaymentKey: 1
iCloudPrompted: 1
hideEmptyFieldsInDetailsView: 1
passwordGenerationSettings: {length = 494, bytes = 0x62706c69 73743030 d4010203 04050629 ... 00000000 00000174 }
AppleITunesStoreItemKinds: (
    "itunes-u",
    movie,
    album,
    ringtone,
    "software-update",
    booklet,
    tone,
    "music-video",
    "tv-episode",
    "tv-season",
    song,
    podcast,
    software,
    audiobook,
    "podcast-episode",
    wemix,
    eBook,
    mix,
    artist,
    document
)
AppleLanguagesDidMigrate: 16A404
autoFillExitedCleanly: 1
installDate: 2018-07-23 21:17:49 +0000
migratedToNewSecretStore: 1
migratedV1Dropbox: 1
failedUnlockAttempts: 0
GMSInstanceID-version: 1.0.10
disallowAllPinCodeOpens: 1
WebDatabaseDirectory: /var/mobile/Containers/Data/Application/9125B169-9C8C-44F1-B6BA-5481514DA520/Library/Caches
mainAppDidChangeDatabases: 1
AKLastCheckInSuccessDate: 2018-10-20 07:56:01 +0000
promptedForReview: 1
GID_AppHasRunBefore: 1
kCSERFKeyObjCSDK: 3FBA346B-C24A-46D1-80FB-CE900D40966B-3874-000007C35DE861C1
WebKitLocalStorageDatabasePathPreferenceKey: /var/mobile/Containers/Data/Application/9125B169-9C8C-44F1-B6BA-5481514DA520/Library/Caches
Ep: 1532380669
Flags: P[1[-1282]110[361]1111]
--------------------
Last Crash
--------------------
--------------------
Sync
--------------------
Ben (Google Drive Sync) => 2021-03-19 14:01:27.243 (61 KB)
Leslie (Google Drive Sync) => 2021-03-22 19:51:22.945 (63 KB)
Ben-HP (iOS Files Sync) => 2020-10-13 20:01:51.000 (8 KB)
--------------------
[Support/AD6DF4B5-35CB-491F-B8BA-16D30086BADB-offline-cache.dat] 57 KB - 6/27/20, 14:26:56
[Support/38339FBA-D881-450B-A762-61023258534A-offline-cache.dat] 48 KB - 7/31/18, 12:53:46
[Support/A3F1B157-9FEB-4DB2-A103-421A54A4E28C-offline-cache.dat] 36 KB - 11/20/18, 11:55:38
[Support/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF-offline-cache.dat] 56 KB - 7/2/20, 17:50:12
[Support/18764F8D-6420-415F-9228-D990EE3FE00B-offline-cache.dat] 49 KB - 11/20/18, 11:54:25
[Support/8C31AEC2-3D9F-43BD-A780-EBFAC4F91C36-offline-cache.dat] 7 KB - 6/18/19, 11:29:41
[Support/1B8FBD7F-BA96-400E-8A5A-431C3D32CFB5-offline-cache.dat] 7 KB - 5/26/20, 16:01:17
[preferences/databases.json] 12 KB - Today, 21:55:37
[.com.apple.mobile_container_manager.metadata.plist] 217 bytes - 10/17/18, 15:54:31
[auto-fill-caches/1B8FBD7F-BA96-400E-8A5A-431C3D32CFB5-autofill-cache.dat] 7 KB - 5/26/20, 16:01:17
[auto-fill-caches/AD6DF4B5-35CB-491F-B8BA-16D30086BADB-autofill-cache.dat] 57 KB - 6/27/20, 14:26:56
[auto-fill-caches/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF-autofill-cache.dat] 56 KB - 7/2/20, 17:50:12
[auto-fill-caches/A60CD6C1-5022-4936-A3C6-B2BB872DDAC6-autofill-cache.dat] 7 KB - 12/4/18, 09:40:05
[auto-fill-caches/8C31AEC2-3D9F-43BD-A780-EBFAC4F91C36-autofill-cache.dat] 7 KB - 6/18/19, 12:49:48
[auto-fill-caches/18764F8D-6420-415F-9228-D990EE3FE00B-autofill-cache.dat] 49 KB - 11/20/18, 11:54:25
[auto-fill-caches/A3F1B157-9FEB-4DB2-A103-421A54A4E28C-autofill-cache.dat] 36 KB - 11/20/18, 11:55:38
[Library/Preferences/group.strongbox.mcguill.plist] 13 KB - Today, 13:17:48
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2020-01-08T17:55:00-07:00.bak] 48 KB - 1/8/20, 17:55:00
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-01-07T16:23:29-07:00.bak] 62 KB - 1/4/21, 09:49:57
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-03-24T13:52:02-06:00.bak] 63 KB - 2/27/21, 14:54:13
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-03-07T13:42:25-07:00.bak] 62 KB - 2/21/21, 23:20:10
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2020-01-08T19:47:19-07:00.bak] 48 KB - 1/8/20, 19:47:19
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2020-01-08T19:46:55-07:00.bak] 48 KB - 1/8/20, 19:46:55
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-02-12T10:19:53-07:00.bak] 62 KB - 1/7/21, 16:24:53
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-01-07T16:24:50-07:00.bak] 62 KB - 1/7/21, 16:23:33
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2020-01-08T19:45:07-07:00.bak] 48 KB - 1/8/20, 19:45:07
[backups/AD6DF4B5-35CB-491F-B8BA-16D30086BADB/2021-02-22T16:31:22-07:00.bak] 62 KB - 2/9/21, 18:39:09
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-02-11T10:58:44-07:00.bak] 61 KB - 2/11/21, 10:58:39
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-03-19T14:01:23-06:00.bak] 61 KB - 3/12/21, 07:03:09
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-03-12T12:53:06-07:00.bak] 61 KB - 3/4/21, 09:43:14
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-02-19T17:08:24-07:00.bak] 61 KB - 2/17/21, 13:39:01
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-02-19T17:02:10-07:00.bak] 61 KB - 2/11/21, 10:58:47
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-02-11T10:46:53-07:00.bak] 61 KB - 2/1/21, 14:27:13
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-03-04T09:43:11-07:00.bak] 61 KB - 3/4/21, 09:42:45
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-03-04T09:42:41-07:00.bak] 61 KB - 3/4/21, 09:06:03
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-02-11T10:58:36-07:00.bak] 61 KB - 2/8/21, 21:57:31
[backups/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF/2021-03-04T09:05:59-07:00.bak] 61 KB - 2/19/21, 17:08:27
[sync-manager/local/AD6DF4B5-35CB-491F-B8BA-16D30086BADB] 63 KB - 3/22/21, 19:51:22
[sync-manager/local/B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF] 61 KB - 3/19/21, 14:01:27
[sync-manager/local/6A908873-FE0F-4F5F-9D49-5180EB3202FD] 824 bytes - 11/13/20, 13:17:22
[sync-manager/local/14D2BF36-E1B5-40E7-97BC-8D28AE7865C1] 8 KB - 10/13/20, 20:01:51
--------------------
[Ben] on [Google Drive] Config
{
    auditConfig =     {
        auditInBackground = 1;
        caseInsensitiveMatchForDuplicates = 1;
        checkForCommonPasswords = 1;
        checkForDuplicatedPasswords = 1;
        checkForMinimumLength = 0;
        checkForNoPasswords = 0;
        checkForSimilarPasswords = 1;
        checkHibp = 0;
        hibpCaveatAccepted = 0;
        hibpCheckForNewBreachesIntervalSeconds = 86400;
        lastKnownAuditIssueCount = 3;
        levenshteinSimilarityThreshold = "0.75";
        minimumLength = 12;
        showAuditPopupNotifications = 1;
        showCachedHibpHits = 1;
    };
    autoFillConvenienceAutoUnlockTimeout = 600;
    autoFillCopyTotp = 1;
    autoFillEnabled = 1;
    autoFillLastUnlockedAt = "638476187.962936";
    autoLockOnDeviceLock = 1;
    autoLockTimeoutSeconds = 600;
    browseItemSubtitleField = 1;
    browseSortField = 1;
    browseSortFoldersSeparately = 1;
    browseSortOrderDescending = 0;
    browseViewType = 0;
    colorizePasswords = 1;
    colorizeProtectedCustomFields = 0;
    conflictResolutionStrategy = 0;
    detailsViewCollapsedSections =     (
        0,
        0,
        0,
        0,
        0,
        0
    );
    doNotShowRecycleBinInBrowse = 0;
    doubleTapAction = 3;
    duressAction = 0;
    easyReadFontForAll = 1;
    emptyOrNilPwPreferNilCheckFirst = 0;
    failedPinAttempts = 0;
    fileIdentifier = 0BwcD0j0uWrgDeW1LV3VKTmNTOVk;
    fileName = "BenPasswords.psafe3";
    forceOpenOffline = 0;
    hasBeenPromptedForConvenience = 1;
    hasBeenPromptedForQuickLaunch = 1;
    hasUnresolvedConflicts = 0;
    hideIconInBrowse = 0;
    hideTotp = 1;
    hideTotpCustomFieldsInViewMode = 1;
    hideTotpInBrowse = 0;
    immediateOfflineOfferIfOfflineDetected = 1;
    immediateSearchOnBrowse = 0;
    isEnrolledForConvenience = 1;
    isTouchIdEnabled = 1;
    keePassIconSet = 0;
    keyFileBookmark = "<Not Set>";
    lastSyncAttempt = "638942112.071754";
    lastSyncRemoteModDate = "637876887.243";
    likelyFormat = 0;
    longPressTapAction = 4;
    makeBackups = 1;
    maxBackupKeepCount = 10;
    nickName = Ben;
    offlineDetectedBehaviour = 0;
    promptedForAutoFetchFavIcon = 0;
    quickTypeDisplayFormat = 0;
    quickTypeEnabled = 1;
    readOnly = 0;
    showChildCountOnFolderInBrowse = 0;
    showEmptyFieldsInDetailsView = 0;
    showExpiredInBrowse = 1;
    showExpiredInSearch = 1;
    showFlagsInBrowse = 1;
    showKeePass1BackupGroup = 0;
    showPasswordByDefaultOnEditScreen = 1;
    showQuickViewExpired = 0;
    showQuickViewFavourites = 1;
    showQuickViewNearlyExpired = 1;
    showRecycleBinInSearchResults = 0;
    storageProvider = 0;
    tapAction = 1;
    tripleTapAction = 5;
    tryDownloadFavIconForNewRecord = 1;
    uuid = "B2C9E17A-7D1A-42BC-8D2E-623E0C0533FF";
}
[Leslie] on [Google Drive] Config
{
    auditConfig =     {
        auditInBackground = 1;
        caseInsensitiveMatchForDuplicates = 1;
        checkForCommonPasswords = 1;
        checkForDuplicatedPasswords = 1;
        checkForMinimumLength = 0;
        checkForNoPasswords = 0;
        checkForSimilarPasswords = 1;
        checkHibp = 0;
        hibpCaveatAccepted = 0;
        hibpCheckForNewBreachesIntervalSeconds = 86400;
        lastKnownAuditIssueCount = 83;
        levenshteinSimilarityThreshold = "0.75";
        minimumLength = 12;
        showAuditPopupNotifications = 1;
        showCachedHibpHits = 1;
    };
    autoFillConvenienceAutoUnlockTimeout = 180;
    autoFillCopyTotp = 1;
    autoFillEnabled = 1;
    autoFillLastUnlockedAt = "638308357.3007489";
    autoLockOnDeviceLock = 1;
    autoLockTimeoutSeconds = 600;
    browseItemSubtitleField = 1;
    browseSortField = 1;
    browseSortFoldersSeparately = 1;
    browseSortOrderDescending = 0;
    browseViewType = 0;
    colorizePasswords = 1;
    colorizeProtectedCustomFields = 0;
    conflictResolutionStrategy = 0;
    detailsViewCollapsedSections =     (
        0,
        0,
        0,
        0,
        0,
        1
    );
    doNotShowRecycleBinInBrowse = 0;
    doubleTapAction = 3;
    duressAction = 0;
    easyReadFontForAll = 1;
    emptyOrNilPwPreferNilCheckFirst = 0;
    failedPinAttempts = 0;
    fileIdentifier = 0BwcD0j0uWrgDeW1LV3VKTmNTOVk;
    fileName = "LesliePasswords.psafe3";
    forceOpenOffline = 0;
    hasBeenPromptedForConvenience = 1;
    hasBeenPromptedForQuickLaunch = 0;
    hasUnresolvedConflicts = 0;
    hideIconInBrowse = 0;
    hideTotp = 0;
    hideTotpCustomFieldsInViewMode = 1;
    hideTotpInBrowse = 0;
    immediateOfflineOfferIfOfflineDetected = 1;
    immediateSearchOnBrowse = 0;
    isEnrolledForConvenience = 1;
    isTouchIdEnabled = 1;
    keePassIconSet = 0;
    keyFileBookmark = "<Not Set>";
    lastSyncAttempt = "638308320.895905";
    lastSyncRemoteModDate = "638157082.9450001";
    likelyFormat = 0;
    longPressTapAction = 4;
    makeBackups = 1;
    maxBackupKeepCount = 10;
    nickName = Leslie;
    offlineDetectedBehaviour = 0;
    promptedForAutoFetchFavIcon = 0;
    quickTypeDisplayFormat = 0;
    quickTypeEnabled = 1;
    readOnly = 0;
    showChildCountOnFolderInBrowse = 0;
    showEmptyFieldsInDetailsView = 1;
    showExpiredInBrowse = 1;
    showExpiredInSearch = 1;
    showFlagsInBrowse = 1;
    showKeePass1BackupGroup = 0;
    showPasswordByDefaultOnEditScreen = 1;
    showQuickViewExpired = 0;
    showQuickViewFavourites = 1;
    showQuickViewNearlyExpired = 1;
    showRecycleBinInSearchResults = 0;
    storageProvider = 0;
    tapAction = 1;
    tripleTapAction = 8;
    tryDownloadFavIconForNewRecord = 1;
    uuid = "AD6DF4B5-35CB-491F-B8BA-16D30086BADB";
}
[Ben-HP] on [iOS Files] Config
{
    auditConfig =     {
        auditInBackground = 1;
        caseInsensitiveMatchForDuplicates = 1;
        checkForCommonPasswords = 1;
        checkForDuplicatedPasswords = 1;
        checkForMinimumLength = 0;
        checkForNoPasswords = 0;
        checkForSimilarPasswords = 0;
        checkHibp = 0;
        hibpCaveatAccepted = 0;
        hibpCheckForNewBreachesIntervalSeconds = 86400;
        lastKnownAuditIssueCount = 2;
        levenshteinSimilarityThreshold = "0.75";
        minimumLength = 12;
        showAuditPopupNotifications = 1;
        showCachedHibpHits = 1;
    };
    autoFillConvenienceAutoUnlockTimeout = "-1";
    autoFillCopyTotp = 1;
    autoFillEnabled = 1;
    autoLockOnDeviceLock = 1;
    autoLockTimeoutSeconds = 60;
    browseItemSubtitleField = 1;
    browseSortField = 1;
    browseSortFoldersSeparately = 1;
    browseSortOrderDescending = 0;
    browseViewType = 0;
    colorizePasswords = 1;
    colorizeProtectedCustomFields = 0;
    conflictResolutionStrategy = 0;
    detailsViewCollapsedSections =     (
        0,
        0,
        0,
        0,
        1,
        1
    );
    doNotShowRecycleBinInBrowse = 0;
    doubleTapAction = 4;
    duressAction = 0;
    easyReadFontForAll = 0;
    emptyOrNilPwPreferNilCheckFirst = 0;
    failedPinAttempts = 0;
    fileIdentifier = "{\"bookMark\":\"Ym9vazgHAAAAAAQQMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAYAAAQAAAADAwAAAAIAAAcAAAABAQAAcHJpdmF0ZQADAAAAAQEAAHZhcgAGAAAAAQEAAG1vYmlsZQAACgAAAAEBAABDb250YWluZXJzAAAGAAAAAQEAAFNoYXJlZAAACAAAAAEBAABBcHBHcm91cCQAAAABAQAAQzg2QTg0OTUtQUMwQi00RTU1LTg2QTEtNThGQzAyREY5RjdEFQAAAAEBAABGaWxlIFByb3ZpZGVyIFN0b3JhZ2UAAAAzAAAAAQEAAGl0ZW18MXxjZDg5YTVkMSUyRGFmNmMlMkQ0YTFmJTJEYmU2MyUyRGFkYTM3Mjg2Njg3ZgANAAAAAQEAAEJlbi1IUC5wc2FmZTMAAAAoAAAAAQYAABAAAAAgAAAALAAAADwAAABQAAAAYAAAAHAAAACcAAAAvAAAAPgAAAAIAAAABAMAABcAAAAAAAAACAAAAAQDAAACAAAAAAAAAAgAAAAEAwAAMwAAAAAAAAAIAAAABAMAAFAIAAAAAAAACAAAAAQDAACKKQAAAAAAAAgAAAAEAwAAiykAAAAAAAAIAAAABAMAAKzaWQMAAAAACAAAAAQDAADc2lkDAAAAAAgAAAAEAwAAq+FZAwAAAAAIAAAABAMAAIHiWQMAAAAAKAAAAAEGAABAAQAAUAEAAGABAABwAQAAgAEAAJABAACgAQAAsAEAAMABAADQAQAACAAAAAAEAABBwptJx4AAABgAAAABAgAAAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAFAAAAAEJAABmaWxlOi8vL3ByaXZhdGUvdmFyLwQAAAABAQAARGF0YQgAAAAEAwAAAFDJmjsAAAAIAAAAAAQAAEHABB1cgM0LJAAAAAEBAAA5MkEwRTY3RS1CRDZFLTQyNDQtOUUxQi1FQ0JENTdGQzYwNDIYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAwAAAABAQAAL3ByaXZhdGUvdmFyCAAAAAEJAABmaWxlOi8vLxMAAAABAQAAU3lzdGVtQHNuYXAtNTQ4MTM1NAAIAAAAAAQAAMHNJ+RAAAAAJAAAAAEBAAA3MTRGM0ZDRC1DQ0YxLTREQzktQkZFMS01RjQxNzRERkJGQjcYAAAAAQIAAIkAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAGAAAAD+\\/\\/\\/\\/APAAAAAAAAAHAAAAAiAAAHADAAAAAAAABSAAAOgCAAAAAAAAECAAAPgCAAAAAAAAESAAACQDAAAAAAAAEiAAAGgCAAAAAAAAEyAAABQDAAAAAAAAICAAAFADAAAAAAAABAAAAAMDAAAA8AAABAAAAAMDAAAAAAAABAAAAAMDAAABAAAALAAAAAEGAADkAwAA8AMAAPwDAADwAwAA8AMAAPADAADwAwAA8AMAAPADAADwAwAA8AMAAJIAAAABAQAAZmlsZXByb3ZpZGVyOiNjb20ubWljcm9zb2Z0LnNreWRyaXZlLm9uZWRyaXZlZmlsZXByb3ZpZGVyLzlkODBlNGQ4LTExYmEtNGQ2Ny04ODg5LTZjMTU5NDYzMGQzYy9pdGVtfDF8Y2Q4OWE1ZDElMkRhZjZjJTJENGExZiUyRGJlNjMlMkRhZGEzNzI4NjY4N2YAAF0BAAABAgAAZWEzMjc5ZWM4NDY5MTcyZmM4NDVkMmRhOGM1NjljZTY3NDg1OWU4NWU4OWUzODcyYjAzZGM1OTA3MGJkN2U2MDswMDswMDAwMDAwMDswMDAwMDAwMDswMDAwMDAwMDswMDAwMDAwMDAwMDAwMDIwO2NvbS5hcHBsZS5hcHAtc2FuZGJveC5yZWFkLXdyaXRlOzAxOzAxMDAwMDA1OzAwMDAwMDAwMDM1OWUyODE7MDE7L3ByaXZhdGUvdmFyL21vYmlsZS9Db250YWluZXJzL1NoYXJlZC9BcHBHcm91cC9DODZBODQ5NS1BQzBCLTRFNTUtODZBMS01OEZDMDJERjlGN0QvRmlsZSBQcm92aWRlciBTdG9yYWdlL2l0ZW18MXxjZDg5YTVkMSUyRGFmNmMlMkQ0YTFmJTJEYmU2MyUyRGFkYTM3Mjg2Njg3Zi9CZW4tSFAucHNhZmUzAAAAAMAAAAD+\\/\\/\\/\\/AQAAAHwDAAAPAAAABBAAABABAAAAAAAABRAAAOABAAAAAAAAEBAAACACAAAAAAAAQBAAABACAAAAAAAAACAAAAgEAAAAAAAAAiAAANQCAAAAAAAABSAAAEACAAAAAAAAECAAAFwCAAAAAAAAESAAAIgCAAAAAAAAEiAAAGgCAAAAAAAAEyAAAHgCAAAAAAAAICAAALQCAAAAAAAAcCAAADwEAAAAAAAAENAAAAQAAAAAAAAAgPAAANgEAAAAAAAA\"}";
    fileName = "Ben-HP.psafe3";
    forceOpenOffline = 0;
    hasBeenPromptedForConvenience = 1;
    hasBeenPromptedForQuickLaunch = 0;
    hasUnresolvedConflicts = 0;
    hideIconInBrowse = 0;
    hideTotp = 0;
    hideTotpCustomFieldsInViewMode = 1;
    hideTotpInBrowse = 0;
    immediateOfflineOfferIfOfflineDetected = 0;
    immediateSearchOnBrowse = 0;
    isEnrolledForConvenience = 1;
    isTouchIdEnabled = 1;
    keePassIconSet = 1;
    keyFileBookmark = "<Not Set>";
    lastSyncRemoteModDate = 624333711;
    likelyFormat = 0;
    longPressTapAction = 3;
    makeBackups = 1;
    maxBackupKeepCount = 10;
    nickName = "Ben-HP";
    offlineDetectedBehaviour = 1;
    promptedForAutoFetchFavIcon = 0;
    quickTypeDisplayFormat = 0;
    quickTypeEnabled = 1;
    readOnly = 1;
    showChildCountOnFolderInBrowse = 1;
    showEmptyFieldsInDetailsView = 0;
    showExpiredInBrowse = 1;
    showExpiredInSearch = 1;
    showFlagsInBrowse = 1;
    showKeePass1BackupGroup = 0;
    showPasswordByDefaultOnEditScreen = 0;
    showQuickViewExpired = 0;
    showQuickViewFavourites = 1;
    showQuickViewNearlyExpired = 1;
    showRecycleBinInSearchResults = 0;
    storageProvider = 5;
    tapAction = 1;
    tripleTapAction = 8;
    tryDownloadFavIconForNewRecord = 1;
    uuid = "14D2BF36-E1B5-40E7-97BC-8D28AE7865C1";
}
--------------------

**Comment by strongbox-mark** [comment] 2021-04-01 10:55
Very difficult to say what could be wrong here @Ben-Voris - Password Safe doesn't offer very good data to work with when doing a merge so it's best effort. 

What do you mean when you say "an old entry will be added"? What is "an old entry"? Where is it located? Is it located in the source database and the destination database? or just the source. If so isn't this expected? 

If not could you compare the ID of the source entry? with the ID in the destination entry? Are they different. Need lots more detail here I'm afraid.

Does the regular addition of a new entry work as you expect?

**Comment by Ben-Voris** [comment] 2021-05-17 03:37
When I say "an old entry will be added", I mean that an entry with the name "R8000 router" already exists. Further, I have **not** recently added an entry with this name. Do note that the "R8000 router" entry is the one that was involved in issue [Two adjacent entries in a Password Safe are displayed as the same but they are not](https://github.com/strongbox-password-safe/Strongbox/issues/463). Whatever you did to fix that problem caused the duplicate entry to disappear with no action on my part. Though, I now see that the Created date was changed.

What I did was to update the password of another entry, "sourceforge". Strongbox correctly showed the "sourceforge" entry as changed but also shows that I've added a entry titled "R8000 router".

The ID displayed for the "R800 router" entry in the two safes are different but the Created and Modified dates are the same.

For the entry that I did change, "sourceforge", the ID and Created date is the same in the two safes is the same and, as expected, the Modified date is different.

When I try to use PasswordSafe to compare my current safe with a backup, I ran into this problem [Compare fails with File Read Error - Unknown error #741](https://github.com/pwsafe/pwsafe/issues/741). Note that Strongbox was the last updater of both the primary and backup safe.

I think I can safely (for low values of "safe") force a sync from Strongbox to Google. But I am concerned that something has very wrong here.

**Comment by strongbox-mark** [comment] 2021-05-17 10:32
OK, yes, I'm afraid it's hard to say what's happening here. If you've got good backups, then you can just force push or pull, whichever you prefer to the remote (Google) and see how things go. It should be perfectly fine. I imagine this is a spurious issue caused by the duplicated ID in #463 - You can always grab any old data you need from your backup, or rollback if there's an issue.

**Comment by Ben-Voris** [comment] 2021-06-16 16:33
For what it's worth, this problem happened twice yesterday, once on each of two devices. Again the same entry was affected. ￼There had been no update to the database on either side.

**Comment by strongbox-mark** [comment] 2021-06-16 17:59
Could you send the sync log to support@strongboxsafe.com?

**Comment by Ben-Voris** [comment] 2021-06-16 23:22
The sink logs on both devices only goes back to late morning, today. I will capture them if this happens again.￼

**Comment by strongbox-mark** [comment] 2022-05-16 11:24
Think we should close this one out for now @Ben-Voris - Please re-open if you see this issue again.

**Closed by strongbox-mark** 2022-05-16 11:24 UTC
